config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :masterplates
  resources :workingplates
  resources :screens
  devise_for :users
  resources :organisms, except: [:show]

  root 'welcome#index'

end

app/models/workingplate.rb
class Workingplate < ActiveRecord::Base
  require 'iconv'
  require 'fileutils'

  belongs_to :masterplate
  belongs_to :user

  scope :with_username, -> { joins(:user).order("workingplates.id").select("workingplates.*,users.username AS user_name") }

  serialize :htd_file_info, Hash

  before_create :set_uuid

  private

  def set_uuid
    self.uuid = UUIDTools::UUID.timestamp_create().to_s
  end

end

app/controllers/workingplates_controller.rb
class WorkingplatesController < ApplicationController
  before_action :set_workingplate, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    if params[:me] == "true"
      @workingplates = Workingplate.with_username.where(:user_id => current_user.id).paginate(:page => params[:page], :per_page => 20)
    elsif params[:status] == "imported"
      @workingplates = Workingplate.with_username.where("user_id = ? AND imported = ?", "#{current_user.id}", true ).paginate(:page => params[:page], :per_page => 20)
    elsif params[:status] == "processing"
      @workingplates = Workingplate.with_username.where("user_id = ? AND processing = ?", "#{current_user.id}", true ).paginate(:page => params[:page], :per_page => 20)
    elsif params[:status] == "unprocessed"
      @workingplates = Workingplate.with_username.where("user_id = ? AND processing = ? AND imported =?", "#{current_user.id}", false, false ).paginate(:page => params[:page], :per_page => 20)
    else
      @workingplates = Workingplate.with_username.paginate(:page => params[:page], :per_page => 20)
    end
  end

  def new
    @workingplate = Workingplate.new
    @masterplate = Masterplate.find(params[:mp_id])
  end


  private
  def set_workingplate
    @workingplate = Workingplate.find(params[:id])
  end

  def workingplate_params
    params.require(:workingplate).permit(:label, :masterplate_id, :user_id, :description)
  end

end

app/views/workingplates/_form.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


= simple_form_for @workingplate, :html => { :class => 'well form-horizontal' } do |f|
  .form-inputs
    = f.input :label, input_html: { value: "#{@masterplate.label}-A and -B" }, disabled: true
    = f.input :description
    = f.input :mp_id, as: :hidden, input_html: { value: @masterplate.id }
  .form-actions
    = f.button :submit, class: 'btn btn-sm btn-success'

app/views/workingplates/index.html.haml
%h1 Workingplates

%div.filter
  .btn-group{:role => "group"}
    %button.btn.btn-sm.btn-default{:type => "button"}
      = link_to "My Workingplates", :action => "index", :me => "true"
    %button.btn.btn-sm.btn-default{:type => "button"}
      = link_to "All Workingplates", :action => "index"
    %button.btn.btn-sm.btn-default{:type => "button"}
      = link_to "Currently Processing", :action => "index", :status => "processing"
    %button.btn.btn-sm.btn-default{:type => "button"}
      = link_to "Imported", :action => "index", :status => "imported"
    %button.btn.btn-sm.btn-default{:type => "button"}
      = link_to "Unprocessed", :action => "index", :status => "unprocessed"

-if @workingplates.present?

  %table.table.table-striped
    %thead
      %tr
        %th Label
        %th Created at
        %th Owner
        %th Actions
    %tbody
      - @workingplates.each do |workingplate|
        %tr
          %td= link_to workingplate.label, workingplate_path(workingplate)
          %td= workingplate.created_at.strftime("%Y-%m-%d")
          %td= workingplate.user_name
          %td
            -if current_user && workingplate.user_id == current_user.id || current_user.admin?
              = link_to 'Edit', edit_workingplate_path(workingplate), :class => 'btn btn-sm'
              = link_to 'Destroy', workingplate_path(workingplate), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-sm btn-danger'
              - if workingplate.imported
                %button.btn.btn-sm.btn-diabled
                  imported
              - elsif workingplate.processing
                = link_to 'Processing', '/sidekiq', :class => 'btn btn-sm btn-warning'
              -else
                = link_to 'Process Images', omeroimport_workingplate_path(workingplate), :class => 'btn btn-success btn-sm'

            -else
              <span class="red">not your plate</span>
  = will_paginate(@workingplates, renderer: BootstrapPagination::Rails)

-else
  %div.no_record
    %p
      There are currently no workingplates present that match your criteria. Use the "Workingplate" link next to one of your
      =link_to 'masterplates', masterplates_path
      to generate some.

app/views/workingplates/new.html.haml
%h1 New Workingplates

= render 'form'

= link_to 'Back', workingplates_path