config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :masterplates
  resources :workingplates
  resources :screens
  devise_for :users
  resources :organisms, except: [:show]

  root 'welcome#index'

end

app/models/screen.rb
class Screen < ActiveRecord::Base

  belongs_to :user
  belongs_to :organism
  has_many   :masterplates, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :organism_id, presence: true

  before_create :set_uuid


  private
  def set_uuid
    self.uuid = UUIDTools::UUID.timestamp_create().to_s
  end
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController
  before_action :set_screen, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /screens
  # GET /screens.json
  def index
    @screens = Screen.all
  end

  # GET /screens/1
  # GET /screens/1.json
  def show
  end

  # GET /screens/new
  def new
    @screen = Screen.new
  end

  # GET /screens/1/edit
  def edit
  end

  # POST /screens
  # POST /screens.json
  def create
    @screen = Screen.new(screen_params)
    @screen.update(user: current_user)

    respond_to do |format|
      if @screen.save
        format.html { redirect_to @screen, notice: 'Screen was successfully created.' }
        format.json { render :show, status: :created, location: @screen }
      else
        format.html { render :new }
        format.json { render json: @screen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screens/1
  # PATCH/PUT /screens/1.json
  def update
    respond_to do |format|
      if @screen.update(screen_params)
        format.html { redirect_to @screen, notice: 'Screen was successfully updated.' }
        format.json { render :show, status: :ok, location: @screen }
      else
        format.html { render :edit }
        format.json { render json: @screen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screens/1
  # DELETE /screens/1.json
  def destroy
    @screen.destroy
    respond_to do |format|
      format.html { redirect_to screens_url, notice: 'Screen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_screen
    @screen = Screen.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def screen_params
    params.require(:screen).permit(:name, :description, :organism_id, :substances)
  end
end

app/helpers/screens_helper.rb
module ScreensHelper

  def organism_name organism
    organism.name
  end

  def organism_description organism
    organism.description
  end

  def user_name screen
    screen.user.firstname || 'not set'
  end
end

app/views/screens/_form.html.haml
= simple_form_for(@screen, html: {class: 'form-horizontal' }) do |f|

  =f.input :name
  =f.input :description
  =f.input :organism_id, collection: Organism.all, as: :radio_buttons
  =f.input :substances, input_html: {value: @screen.substances || AppConfig.substances}

  =f.button :submit, class: 'btn btn-sm btn-success'

app/views/screens/edit.html.haml
%h2 Update Screen
=render 'form'

app/views/screens/index.html.haml
-content_for :sidebar_title do
  Create A New Screen
- content_for :sidebar do
  %p
  %ul
    %li use the "New" button to create a new screen
    %li each screen has masterplates
    %li click on the name of a screen to see masterplates associated with the screen

%h1 Screens
= link_to 'New', new_screen_path, :class => 'btn btn-success btn-sm right'
%div.filter
  %p
    = link_to "All Screens", :action => "index"
    |
    = link_to "My Screens", :action => "index", :me => "true"


-if @screens.length > 0
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Description
        %th Created at
        %th Owner
        %th Actions
    %tbody
      - @screens.each do |screen|
        %tr
          %td= link_to screen.name, screen_path(screen)
          %td.max_width
            -if screen.description.present?
              = truncate(screen.description, :length => 120, separator: ' ')
          %td
            = screen.created_at.strftime("%Y-%m-%d")
          %td
            = user_name screen
          %td
            -if current_user && screen.user_id == current_user.id || current_user.admin?
              = link_to 'Edit', edit_screen_path(screen), :class => 'btn btn-xs'
              = link_to 'Destroy', screen_path(screen), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-xs btn-danger'
            -else
              %p
                <span class="red">not your screen</span>
-else
  %p
    %br
  %div.no_record
    %p
      There are no screens on record, please
      =link_to 'create one', new_screen_path, class: 'btn btn-sm btn-success'

app/views/screens/new.html.haml
%h2 New Screen
=render 'form'

app/views/screens/show.html.haml
-#
  Copyright (C) 2012 Juergen Helmers - All Rights Reserved
  You may not use, distribute and modify this code under any
  circumstance without the written permission of the author.

  Juergen Helmers <juergen.helmers@gmail.com>


%h1= "Screen #{@screen.name}"
%dl.dl-horizontal
  %dt
    Name
  %dd
    = @screen.name
  %dt
    Description
  %dd
    = @screen.description
  %dt
    Organism
  %dd
    = organism_description @screen.organism
    %i
      = "(#{organism_name @screen.organism})"
  %dt
    Owner
  %dd
    = @screen.user.fullname
  %dt
    Control Substances
  %dd.text_left
    -if @screen.substances.present?
      = @screen.substances.split(",").join(", ")



%div.clear
%div.spacer20
%h3
  Masterplates

%p
  -if @screen.masterplates.present?
    = @screen.masterplates.order("label ASC").map{|m| link_to m.label, m }.join(", ").html_safe

  -else
    %p
      No masterplates in this screen,
      =link_to 'create some now', new_masterplate_path
.form-actions
  = link_to 'Back', screens_path, :class => 'btn btn-default btn-sm', :me => true
  -#-if current_user && @screen.user_id == current_user.id || current_user.admin?
  = link_to 'Edit', edit_screen_path(@screen), :class => 'btn btn-success btn-sm'
  = link_to 'Delete', screen_path(@screen), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-sm btn-danger'