config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :masterplates
  resources :workingplates
  resources :screens
  devise_for :users
  resources :organisms, except: [:show]

  root 'welcome#index'

end

app/models/masterplate.rb
class Masterplate < ActiveRecord::Base

  belongs_to :screen
  belongs_to :user
  has_many :masterwells, dependent: :destroy
  has_many :workingplates, :dependent => :destroy

  before_create :set_uuid

  #create virtual attribute for file name
  attr_accessor :masterplate_annotation_file

  validates_presence_of :label, :on => :create, :message => "can't be blank"
  validates_presence_of :masterplate_annotation_file, :on => :create, :message => "can't be blank"

  # scopes
  scope :with_user_and_screen_name, -> { joins(:user).joins(:screen).order("masterplates.id").select("masterplates.*,users.username AS user_name, screens.name AS screen_name") }

  def set_uuid
    self.uuid = UUIDTools::UUID.timestamp_create().to_s
  end

end

app/controllers/masterplates_controller.rb
class MasterplatesController < ApplicationController
  before_action :set_masterplate, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    if params[:me] == "true"
      @masterplates =Masterplate.where(:user_id => current_user.id).paginate(:page => params[:page], :per_page => 20)
    else
      @masterplates = Masterplate.all.paginate(:page => params[:page], :per_page => 20)
    end

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    respond_with(@masterplate)
  end

  def new
    @masterplate = Masterplate.new
    respond_with(@masterplate)
  end

  def edit
  end

  def create
    if required_params?
      @masterplate = MasterplateFactory.new(masterplate_params, current_user).create
    else
      message = ["The following fields have to be specified:"]
      if masterplate_params[:masterplate_annotation_file].blank?
        message << "Spreadsheet input file"
      end
      if masterplate_params[:label].blank?
        message << "Label root"
      end
      if masterplate_params[:screen_id].blank?
        message << "Screen"
      end
      redirect_to new_masterplate_path, alert: "#{message.join(", ")}." and return
    end

    if @masterplate.save
      respond_with(@masterplate, notice: 'Masterplates successfully created.')
    else
      redirect_to new_masterplate_path
    end

  end

  def update
    @masterplate.update(masterplate_params)
    respond_with(@masterplate)
  end

  def destroy
    @masterplate.destroy
    respond_with(@masterplate)
  end

  private
    def set_masterplate
      @masterplate = Masterplate.find(params[:id])
    end

    def masterplate_params
      params.require(:masterplate).permit(:label, :screen_id, :user_id, :description, :masterplate_annotation_file)
    end

    def required_params?
      masterplate_params[:masterplate_annotation_file].present? && masterplate_params[:label].present? &&  masterplate_params[:screen_id].present?
    end

end

app/helpers/masterplates_helper.rb
module MasterplatesHelper
end

app/views/masterplates/_form.html.haml
= simple_form_for @masterplate, html: { :class => 'form-horizontal' } do |f|

  .form-inputs
    = f.input :label, required: true
    = f.input :screen_id, collection: current_user.screens, required: true
    -if action_name == 'new'
      = f.input :masterplate_annotation_file, as: :file, required: true
    = f.input :description

  .form-actions
    = f.button :submit, class: 'btn btn-sm btn-success'

app/views/masterplates/edit.html.haml
%h1 Editing masterplate

= render 'form'

= link_to 'Show', @masterplate
\|
= link_to 'Back', masterplates_path

app/views/masterplates/index.html.haml
- content_for :sidebar_title do
  Masterplates
- content_for :sidebar do
  %p
  %ul
    %li use the "New" button to create a new set of masterplates:
    %ul
      %li each masterplate belongs to a screen
      %li click on the name of a masterplate to see the plate layout
      %li click on the green "generate Workingplates" or "generate more Workingplates" button to create a set of working plates.

%h1 Masterplates

-if current_user.screens.count > 0
  = link_to 'New', new_masterplate_path, :class => 'btn btn-sm btn-success pull-right'
-else
  = link_to 'New', '#', :class => 'btn btn-sm btn-disabled pull-right', :disable => true

%div.filter
  .btn-group{:role => "group"}
    %button.btn.btn-sm.btn-default{:type => "button"}
      = link_to "My Masterplates", :action => "index", :me => "true"
    %button.btn.btn-sm.btn-default{:type => "button"}
      = link_to "All Masterplates", :action => "index"

-if @masterplates.size > 0
  %table.table.table-striped
    %thead
      %tr
        %th label
        %th Created at
        %th Screen
        %th Owner
        %th Actions
    %tbody
      - @masterplates.each do |masterplate|
        %tr
          %td= link_to masterplate.label, masterplate_path(masterplate)
          %td= masterplate.created_at.strftime("%Y-%m-%d")
          %td= link_to masterplate.screen.name, masterplate.screen
          %td= masterplate.user.fullname
          -if current_user && masterplate.user_id == current_user.id || current_user.admin?
            %td= link_to 'Delete', masterplate_path(masterplate), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-xs btn-danger'
            -unless masterplate.workingplates.size > 0
              %td= link_to 'generate Workingplates', new_workingplate_path(:mp_id => masterplate.id), :class => 'btn btn-xs btn-success'
            -else
              %td= link_to 'generate more Workingplates', new_workingplate_path(:mp_id => masterplate.id), :class => 'btn btn-xs btn-success'

          -else
            %td
              <span class="red">not your plate</span>
  = will_paginate(@masterplates, renderer: BootstrapPagination::Rails)

-else
  %p
    %br
  %div.no_record
    -if current_user.screens.length > 0
      %p
        There are no masterplates on record, please
        =link_to 'create some', new_masterplate_path
        !
    -else
      %p
        There are no masterplates on record and you haven't created a screen yet.
        =link_to 'Please create  a screen', new_screen_path
        first and then some masterplates!

app/views/masterplates/new.html.haml
%h2 New Masterplate

= render 'form'

= link_to 'Back', masterplates_path

app/views/masterplates/show.html.haml
%p#notice= notice

%h2= "Masterplate #{@masterplate.label}"

%dl.dl-horizontal
  %dt Uuid:
  %dd= @masterplate.uuid
  %dt Label:
  %dd= @masterplate.label
  %dt Screen:
  %dd= link_to @masterplate.screen.name, @masterplate.screen
  %dt Description:
  %dd= @masterplate.description
  %dt User:
  %dd= @masterplate.user.fullname

%p
  = link_to 'Back', masterplates_path, class: 'btn btn-sm btn-default'
  = link_to 'Edit', edit_masterplate_path(@masterplate), class: 'btn btn-sm btn-success'
  = link_to 'Delete', masterplate_path(@masterplate), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-sm btn-danger'


%p
  .masterplate.drop-shadow.raised
    - counter = 0
    - while counter < 96
      - w = @masterplate.masterwells[counter]
      - if w.present?
        %div{:class => "masterwell #{'full' unless w.metadata_records.blank?}", data: {animation: "true", placement: "top", trigger: "hover", html: "true", title: "#{w.name}",content: "#{master_popover(w)}"}}
          = w.name
      -else
        %div{:class => "masterwell"}
      - counter += 1