config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :masterplates
  resources :workingplates
  resources :screens
  devise_for :users
  resources :organisms, except: [:show]

  root 'welcome#index'

end

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Mhlanga Lab Screening
    / Collect the nav links, forms, and other content for toggling
    - if current_user
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li.active
            =link_to 'Screens', screens_path
          %li
            %a{:href => "#"} Link
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Screen Plates
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                =link_to 'Masterplates', masterplates_path
                =link_to 'Workingplates', workingplates_path
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Admin
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                =link_to 'Organisms', organisms_path
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider
              %li
                %a{:href => "#"} Separated link
              %li.divider
              %li
                %a{:href => "#"} One more separated link
          %li= link_to 'Logout', destroy_user_session_path, :method => :delete
        %form.navbar-form.navbar-right{:role => "search"}
          .form-group
            %input.form-control{:placeholder => "Search", :type => "text"}/
          %button.btn.btn-default{:type => "submit"} Submit
    -else
      %ul.nav.navbar-nav
        %li= link_to "Login", new_user_session_path